os: linux
sudo: required
language: c
services:
- docker
script:
- docker build -t project .
after_success: |
  cd "$TRAVIS_BUILD_DIR"
  docker run project tar -c -O target/doc | tar -x
deploy:
  verbose: true
  provider: pages
  local-dir: target/doc
  skip-cleanup: true
  github-token: $GITHUB_API_KEY
  keep-history: false
